export const departamentosYCiudades = {
  "Amazonas": [
    "Leticia",
    "Puerto Nariño"
  ],
  "Antioquia": [
    "Medellín",
    "Bello",
    "Itagüí",
    "Envigado",
    "Apartadó",
    "Turbo",
    "Rionegro",
    "Sabaneta",
    "La Estrella",
    "Copacabana",
    "Girardota",
    "Barbosa",
    "Caldas",
    "La Ceja",
    "El Carmen de Viboral",
    "Marinilla",
    "El Retiro",
    "Guarne",
    "San Pedro de los Milagros",
    "Caucasia",
    "Necoclí",
    "Arboletes",
    "San Juan de Urabá",
    "Chigorodó",
    "Carepa",
    "Mutatá",
    "Vigía del Fuerte"
  ],
  "Arauca": [
    "Arauca",
    "Tame",
    "Saravena",
    "Fortul",
    "Puerto Rondón",
    "Cravo Norte",
    "Arauquita"
  ],
  "Atlántico": [
    "Barranquilla",
    "Soledad",
    "Malambo",
    "Sabanagrande",
    "Puerto Colombia",
    "Galapa",
    "Baranoa",
    "Sabanalarga",
    "Santo Tomás",
    "Palmar de Varela",
    "Ponedera",
    "Usiacurí",
    "Candelaria",
    "Repelón",
    "Manatí",
    "Campo de la Cruz",
    "Santa Lucía",
    "Suan",
    "Piojó",
    "Tubará",
    "Juan de Acosta",
    "Luruaco"
  ],
  "Bolívar": [
    "Cartagena",
    "Magangué",
    "Turbaco",
    "El Carmen de Bolívar",
    "Arjona",
    "Mompós",
    "San Pablo",
    "Santa Rosa del Sur",
    "Simití",
    "Morales",
    "Santa Rosa",
    "Mahates",
    "San Jacinto",
    "María la Baja",
    "San Juan Nepomuceno",
    "Córdoba",
    "Clemencia",
    "Santa Catalina",
    "Soplaviento",
    "Calamar",
    "Villanueva",
    "San Cristóbal",
    "San Estanislao",
    "Río Viejo",
    "Hatillo de Loba",
    "Altos del Rosario",
    "Barranco de Loba",
    "Cicuco",
    "Talaigua Nuevo",
    "Tiquisio",
    "Montecristo",
    "Pinillos",
    "Regidor",
    "San Fernando",
    "San Martín de Loba",
    "Norosí",
    "Arenal",
    "Margarita",
    "San Jacinto del Cauca",
    "Achí",
    "Cantagallo",
    "Puerto Wilches",
    "Morales"
  ],
  "Boyacá": [
    "Tunja",
    "Duitama",
    "Sogamoso",
    "Chiquinquirá",
    "Paipa",
    "Villa de Leyva",
    "Barbosa",
    "Moniquirá",
    "Puerto Boyacá",
    "Santa Rosa de Viterbo",
    "Nobsa",
    "Garagoa",
    "San José de Pare",
    "Ráquira",
    "Tibasosa",
    "Samacá",
    "Combita",
    "Ventaquemada",
    "Oicatá",
    "Toca",
    "Firavitoba",
    "Corrales",
    "Iza",
    "Cuitiva",
    "Pesca",
    "Tópaga",
    "Mongua",
    "Gámeza",
    "Tasco",
    "Betéitiva",
    "Busbanzá",
    "Floresta",
    "Cerinza",
    "Belén",
    "Tutazá",
    "Santa Rosa de Viterbo",
    "Sutamarchán",
    "Tinjacá",
    "Chitaraque",
    "Togüí",
    "Arcabuco",
    "Gachantivá",
    "San Miguel de Sema",
    "Caldas",
    "Buenavista",
    "Coper",
    "La Victoria",
    "Maripí",
    "Muzo",
    "Otanche",
    "Pauna",
    "Quípama",
    "San Pablo de Borbur",
    "Briceño",
    "La Capilla",
    "Maripi",
    "Saboyá",
    "San Miguel de Sema",
    "Caldas"
  ],
  "Caldas": [
    "Manizales",
    "Chinchiná",
    "Villamaría",
    "La Dorada",
    "Riosucio",
    "Anserma",
    "Palestina",
    "Aguadas",
    "Pacora",
    "Salamina",
    "Aranzazu",
    "Neira",
    "Filadelfia",
    "Supía",
    "Marmato",
    "San José",
    "Belalcázar",
    "Risaralda",
    "Viterbo",
    "La Merced",
    "Manzanares",
    "Marquetalia",
    "Marulanda",
    "Pensilvania",
    "Samaná",
    "Victoria"
  ],
  "Caquetá": [
    "Florencia",
    "San Vicente del Caguán",
    "La Montañita",
    "El Paujil",
    "Cartagena del Chairá",
    "Puerto Rico",
    "Belén de los Andaquíes",
    "Albania",
    "Curillo",
    "El Doncello",
    "Morelia",
    "Milán",
    "San José del Fragua",
    "Solano",
    "Solita",
    "Valparaíso"
  ],
  "Casanare": [
    "Yopal",
    "Aguazul",
    "Villanueva",
    "Tauramena",
    "Monterrey",
    "Sabanalarga",
    "Maní",
    "Trinidad",
    "Hato Corozal",
    "Paz de Ariporo",
    "Pore",
    "Támara",
    "San Luis de Palenque",
    "Chámeza",
    "Recetor",
    "Sacama",
    "La Salina",
    "Orocué",
    "Nunchía"
  ],
  "Cauca": [
    "Popayán",
    "Santander de Quilichao",
    "Puerto Tejada",
    "Corinto",
    "Miranda",
    "Guachené",
    "Villa Rica",
    "Padilla",
    "Caloto",
    "Piendamó",
    "Silvia",
    "Morales",
    "Buenos Aires",
    "Suárez",
    "Cajibío",
    "El Tambo",
    "Timbío",
    "Rosas",
    "La Sierra",
    "Sotará",
    "Puracé",
    "Almaguer",
    "San Sebastián",
    "La Vega",
    "Florencia",
    "Mercaderes",
    "Patía",
    "Balboa",
    "Argelia",
    "Bolívar",
    "Sucre",
    "Santa Rosa",
    "Timbiquí",
    "López de Micay",
    "Guapi"
  ],
  "Cesar": [
    "Valledupar",
    "Aguachica",
    "Bosconia",
    "Codazzi",
    "La Paz",
    "San Diego",
    "La Jagua de Ibirico",
    "Curumaní",
    "Chimichagua",
    "Chiriguaná",
    "El Paso",
    "Astrea",
    "Becerril",
    "Copey",
    "González",
    "La Gloria",
    "Manaure",
    "Pailitas",
    "Pelaya",
    "Pueblo Bello",
    "Río de Oro",
    "San Alberto",
    "San Martín",
    "Tamalameque"
  ],
  "Chocó": [
    "Quibdó",
    "Istmina",
    "Condoto",
    "Tadó",
    "Acandí",
    "Riosucio",
    "Unguía",
    "Bahía Solano",
    "Nuquí",
    "Lloró",
    "El Cantón del San Pablo",
    "San José del Palmar",
    "Novita",
    "Río Iró",
    "Río Quito",
    "Cértegui",
    "Unión Panamericana",
    "Bagadó",
    "Bojayá",
    "El Litoral del San Juan",
    "Medio Atrato",
    "Medio Baudó",
    "Medio San Juan",
    "Nóvita",
    "Nuquí",
    "Río Iró",
    "Río Quito",
    "San José del Palmar",
    "Sipí",
    "Tadó",
    "Unguía"
  ],
  "Córdoba": [
    "Montería",
    "Cereté",
    "Lorica",
    "Sahagún",
    "Planeta Rica",
    "Montelíbano",
    "Tierralta",
    "Ayapel",
    "Ciénaga de Oro",
    "Chinú",
    "Cotorra",
    "La Apartada",
    "Los Córdobas",
    "Momil",
    "Moñitos",
    "Pueblo Nuevo",
    "Puerto Escondido",
    "Puerto Libertador",
    "Purísima",
    "San Andrés de Sotavento",
    "San Antero",
    "San Bernardo del Viento",
    "San Carlos",
    "San José de Uré",
    "San Pelayo",
    "Tuchín",
    "Valencia"
  ],
  "Cundinamarca": [
    "Bogotá",
    "Soacha",
    "Girardot",
    "Zipaquirá",
    "Facatativá",
    "Chía",
    "Madrid",
    "Funza",
    "Cajicá",
    "Sibaté",
    "Tocancipá",
    "La Calera",
    "Sopó",
    "Tabio",
    "Tenjo",
    "Cota",
    "Gachancipá",
    "Nemocón",
    "Cogua",
    "Subachoque",
    "El Rosal",
    "Pacho",
    "La Palma",
    "Yacopí",
    "Villagómez",
    "Supatá",
    "San Cayetano",
    "Vergara",
    "Nimaima",
    "Nocaima",
    "Quebradanegra",
    "Útica",
    "Caparrapí",
    "Guaduas",
    "Puerto Salgar",
    "Albán",
    "La Vega",
    "Sasaima",
    "Villeta",
    "Bituima",
    "Vianí",
    "Chaguaní",
    "Pulí",
    "San Juan de Río Seco",
    "Tena",
    "La Mesa",
    "Anapoima",
    "Anolaima",
    "Cachipay",
    "El Colegio",
    "San Antonio del Tequendama",
    "Tequendama",
    "Apulo",
    "Tocaima",
    "Agua de Dios",
    "Ricaurte",
    "Nilo",
    "Jerusalén",
    "Tibacuy",
    "Venecia",
    "San Bernardo",
    "Pandi",
    "Arbeláez",
    "Fusagasugá",
    "Silvania",
    "Granada",
    "Pasca",
    "Cabrera",
    "Gutiérrez",
    "Ubaque",
    "Fosca",
    "Chipaque",
    "Une",
    "Cáqueza",
    "Quetame",
    "Guayabetal",
    "Junín",
    "Gachalá",
    "Gama",
    "Ubalá",
    "Gachetá",
    "Chocontá",
    "Villapinzón",
    "Lenguazaque",
    "Guachetá",
    "Ráquira",
    "Samacá",
    "Ventaquemada",
    "Turmequé",
    "Nuevo Colón",
    "Borbur",
    "Otanche",
    "San Pablo de Borbur",
    "Caldas",
    "Maripí",
    "Muzo",
    "Coper",
    "La Victoria",
    "Pauna",
    "Briceño"
  ],
  "Guainía": [
    "Inírida",
    "Barranco Minas",
    "Mapiripana",
    "San Felipe",
    "Puerto Colombia",
    "La Guadalupe",
    "Cacahual",
    "Pana Pana",
    "Morichal"
  ],
  "Guaviare": [
    "San José del Guaviare",
    "Calamar",
    "El Retorno",
    "Miraflores"
  ],
  "Huila": [
    "Neiva",
    "Pitalito",
    "Garzón",
    "La Plata",
    "Campoalegre",
    "Aipe",
    "Palermo",
    "Rivera",
    "Tello",
    "Baraya",
    "Villavieja",
    "Algeciras",
    "Isnos",
    "San Agustín",
    "Saladoblanco",
    "Tarqui",
    "Gigante",
    "Hobo",
    "Yaguará",
    "Tesalia",
    "Paicol",
    "Nátaga",
    "Iquira",
    "Teruel",
    "Santa María",
    "Suaza",
    "Acevedo",
    "Guadalupe",
    "Timaná",
    "Elías",
    "Oporapa",
    "Altamira",
    "Agrado"
  ],
  "La Guajira": [
    "Riohacha",
    "Maicao",
    "Valledupar",
    "San Juan del Cesar",
    "Villanueva",
    "Fonseca",
    "Barrancas",
    "Distracción",
    "El Molino",
    "Hatonuevo",
    "La Jagua del Pilar",
    "Manaure",
    "Uribia",
    "Dibulla",
    "Albania"
  ],
  "Magdalena": [
    "Santa Marta",
    "Ciénaga",
    "El Banco",
    "Fundación",
    "Plato",
    "Zona Bananera",
    "Aracataca",
    "Pivijay",
    "Sabanas de San Ángel",
    "Cerro San Antonio",
    "Chivolo",
    "Concordia",
    "El Piñón",
    "El Retén",
    "Guamal",
    "Nueva Granada",
    "Pedraza",
    "Pijiño del Carmen",
    "Puebloviejo",
    "Remolino",
    "Salamina",
    "San Sebastián de Buenavista",
    "San Zenón",
    "Santa Ana",
    "Santa Bárbara de Pinto",
    "Sitionuevo",
    "Tenerife",
    "Zapayán",
    "Algarrobo"
  ],
  "Meta": [
    "Villavicencio",
    "Acacías",
    "Granada",
    "San Martín",
    "Puerto López",
    "Cumaral",
    "Restrepo",
    "El Calvario",
    "San Carlos de Guaroa",
    "Castilla la Nueva",
    "Cabuyaro",
    "Barranca de Upía",
    "Paratebueno",
    "Medina",
    "Uribe",
    "Lejanías",
    "El Castillo",
    "El Dorado",
    "Cubarral",
    "Guamal",
    "San Juan de Arama",
    "Mesetas",
    "La Macarena",
    "Vistahermosa",
    "Puerto Concordia",
    "Puerto Lleras",
    "Puerto Rico",
    "Mapiripán",
    "Fuente de Oro"
  ],
  "Nariño": [
    "Pasto",
    "Tumaco",
    "Ipiales",
    "Túquerres",
    "Samaniego",
    "Sandona",
    "La Unión",
    "Tangua",
    "Yacuanquer",
    "Consacá",
    "Nariño",
    "La Florida",
    "Chachagüí",
    "Buesaco",
    "San Lorenzo",
    "Arboleda",
    "Policarpa",
    "Cumbitara",
    "Los Andes",
    "Sotomayor",
    "Taminango",
    "San Pablo",
    "Belén",
    "San Bernardo",
    "Colón",
    "San Pedro de Cartago",
    "La Tola",
    "El Charco",
    "Leiva",
    "La Cruz",
    "Guachucal",
    "Cuaspud",
    "Aldana",
    "Córdoba",
    "Potosí",
    "Puerres",
    "Gualmatán",
    "Funes",
    "Contadero",
    "Iles",
    "Carlosama",
    "Ospina",
    "Imués",
    "Ricaurte",
    "Barbacoas",
    "Roberto Payán",
    "Magüí",
    "Mallama",
    "Providencia",
    "La Llanada",
    "Sapuyes",
    "Ancuyá",
    "Linares",
    "Francisco Pizarro",
    "Mosquera",
    "Olaya Herrera",
    "Santa Bárbara",
    "Sandoná",
    "Yacuanquer"
  ],
  "Norte de Santander": [
    "Cúcuta",
    "Ocaña",
    "Pamplona",
    "Villa del Rosario",
    "Los Patios",
    "Tibú",
    "El Zulia",
    "San Cayetano",
    "Puerto Santander",
    "Villa Caro",
    "Sardinata",
    "Convención",
    "El Tarra",
    "Teorama",
    "Hacarí",
    "La Playa",
    "Ábrego",
    "La Esperanza",
    "Chinácota",
    "Ragonvalia",
    "Herrán",
    "Toledo",
    "Mutiscua",
    "Labateca",
    "Silos",
    "Chitagá",
    "Cácota",
    "Cáchira",
    "Salazar",
    "Arboledas",
    "Cucutilla",
    "Lourdes",
    "Santiago",
    "Villa Caro",
    "Bucarasica",
    "Puerto Santander",
    "Gramalote",
    "Durania",
    "Bochalema"
  ],
  "Putumayo": [
    "Mocoa",
    "Puerto Asís",
    "Valle del Guamuez",
    "Orito",
    "Puerto Caicedo",
    "Puerto Guzmán",
    "Leguízamo",
    "Sibundoy",
    "San Francisco",
    "San Miguel",
    "Santiago",
    "Colón",
    "Villagarzón"
  ],
  "Quindío": [
    "Armenia",
    "Calarcá",
    "Circasia",
    "Filandia",
    "La Tebaida",
    "Montenegro",
    "Quimbaya",
    "Salento",
    "Córdoba",
    "Buenavista",
    "Génova",
    "Pijao"
  ],
  "Risaralda": [
    "Pereira",
    "Dosquebradas",
    "Santa Rosa de Cabal",
    "La Virginia",
    "Marsella",
    "Belén de Umbría",
    "Quinchía",
    "Pueblo Rico",
    "Guática",
    "Santuario",
    "Apía",
    "Balboa",
    "Mistrató",
    "La Celia"
  ],
  "San Andrés y Providencia": [
    "San Andrés",
    "Providencia"
  ],
  "Santander": [
    "Bucaramanga",
    "Floridablanca",
    "Girón",
    "Piedecuesta",
    "Barrancabermeja",
    "San Gil",
    "Socorro",
    "Málaga",
    "Barbosa",
    "Vélez",
    "Charalá",
    "Simacota",
    "Valle de San José",
    "Contratación",
    "Guadalupe",
    "Gámbita",
    "Villanueva",
    "Guapotá",
    "Suaita",
    "Aguada",
    "Albania",
    "Aratoca",
    "Cabrera",
    "Carcasí",
    "Cepitá",
    "Cerrito",
    "Coromoro",
    "Curití",
    "Encino",
    "Galán",
    "Guaca",
    "Macaravita",
    "Mogotes",
    "Ocamonte",
    "Onzaga",
    "Palmar",
    "Palmas del Socorro",
    "Páramo",
    "Pinchote",
    "Puente Nacional",
    "San Joaquín",
    "San José de Miranda",
    "San Miguel",
    "Santa Helena del Opón",
    "Sucre",
    "Tona",
    "Valle de San José",
    "Villanueva",
    "Zapatoca",
    "La Paz",
    "El Peñón",
    "Jesús María",
    "Jordán",
    "La Belleza",
    "Landázuri",
    "Puerto Parra",
    "Puerto Wilches",
    "Rionegro",
    "Sabana de Torres",
    "San Vicente de Chucurí",
    "Santa Helena del Opón",
    "Simacota",
    "El Carmen de Chucurí",
    "Cimitarra",
    "El Peñón",
    "Bolívar",
    "Florián",
    "Lebrija",
    "Los Santos",
    "Matanza",
    "Palmas del Socorro",
    "Rionegro",
    "San Andrés",
    "Santa Bárbara",
    "Suratá",
    "Vetas",
    "California",
    "Charta",
    "El Playón",
    "Tona"
  ],
  "Sucre": [
    "Sincelejo",
    "Corozal",
    "Sampués",
    "San Marcos",
    "Tolú",
    "Coveñas",
    "Ovejas",
    "Los Palmitos",
    "Galeras",
    "El Roble",
    "Buenavista",
    "Coloso",
    "Chalán",
    "Morroa",
    "Sucre",
    "San Pedro",
    "Since",
    "Majagual",
    "Guaranda",
    "La Unión",
    "San Benito Abad",
    "Caimito"
  ],
  "Tolima": [
    "Ibagué",
    "Espinal",
    "Melgar",
    "Honda",
    "Líbano",
    "Mariquita",
    "Purificación",
    "Guamo",
    "Saldaña",
    "Chaparral",
    "Flandes",
    "Girardot",
    "Planadas",
    "Rioblanco",
    "Ataco",
    "Natagaima",
    "Coyaima",
    "Ortega",
    "Dolores",
    "Alpujarra",
    "Alvarado",
    "Ambalema",
    "Anzoátegui",
    "Armero",
    "Cajamarca",
    "Carmen de Apicalá",
    "Casabianca",
    "Coello",
    "Coyaima",
    "Cunday",
    "Falan",
    "Fresno",
    "Herveo",
    "Icononzo",
    "Lérida",
    "Murillo",
    "Palocabildo",
    "Piedras",
    "Prado",
    "Roncesvalles",
    "Rovira",
    "San Antonio",
    "San Luis",
    "Santa Isabel",
    "Suárez",
    "Valle de San Juan",
    "Venadillo",
    "Villahermosa",
    "Villarrica"
  ],
  "Valle del Cauca": [
    "Cali",
    "Palmira",
    "Buenaventura",
    "Tuluá",
    "Cartago",
    "Buga",
    "Jamundí",
    "Yumbo",
    "Candelaria",
    "Florida",
    "Pradera",
    "Roldanillo",
    "La Unión",
    "Zarzal",
    "Sevilla",
    "Caicedonia",
    "Andalucía",
    "Bugalagrande",
    "Obando",
    "La Victoria",
    "Alcalá",
    "Ulloa",
    "Versalles",
    "El Águila",
    "Toro",
    "San Pedro",
    "Bolívar",
    "Trujillo",
    "Riofrio",
    "Calima",
    "Dagua",
    "La Cumbre",
    "Vijes",
    "Yotoco",
    "Restrepo",
    "Ginebra",
    "Guacarí",
    "El Cerrito",
    "Argelia",
    "El Cairo",
    "Ansermanuevo",
    "El Dovio"
  ],
  "Vaupés": [
    "Mitú",
    "Carurú",
    "Pacoa",
    "Taraira",
    "Papunaua",
    "Yavaraté"
  ],
  "Vichada": [
    "Puerto Carreño",
    "La Primavera",
    "Santa Rosalía",
    "Cumaribo"
  ]
}

export const departamentos = Object.keys(departamentosYCiudades)

export const getCiudadesByDepartamento = (departamento: string): string[] => {
  return departamentosYCiudades[departamento as keyof typeof departamentosYCiudades] || []
}